### ISSUE TITLE
tons of ReferenceErrors when running jasmine via rake

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/curation_concerns#934]
see https://gist.github.com/hackmastera/55a97346bd465bd0f9bd534874b20771

to replicate: 

- start jasmine using `rake curation_concerns:jasmine`
- visit port 8888. jasmine tests will run. for me, 20/23 are failing.

This must be a configuration issue somehow because rspec runs them fine.

**Comment by jcoyne** [comment]
@hackmastera can you do a git bisect and determine which commit broke it?

**Comment by hackmastera** [comment]
yes, good idea.

**Comment by hackmastera** [comment]
i tried to install v1.3.2. I get the following:
```
rake aborted!
NoMethodError: undefined method `helper' for ActionController::API:Class
/home/ubuntu/src/curation_concerns/.internal_test_app/config/environment.rb:5:in `<top (required)>'
/home/ubuntu/src/curation_concerns/tasks/jasmine.rake:9:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => curation_concerns:jasmine
(See full trace by running task with --trace)
```

**Comment by hackmastera** [comment]
just a note here, as i look for something i can both build and mark 'bad' for git bisect... 'ccf75db' is showing the same failures originally reported.

**Comment by hackmastera** [comment]
Looks like this is caused by the same es6 preprocessor issues as https://github.com/projecthydra/curation_concerns/issues/896 was. everything is fine on `ccf75db` When I use hydra-editor 2.0.

**Comment by hackmastera** [comment]
Okay. With cc at `ccf75db`, https://github.com/projecthydra/hydra-editor/commit/d38f1e7 introduces one error into cc, pasted below. The hydra-editor commit before this one gives passing tests.

At the next cc commit, `e6e9f74`, the one where @tpendragon refactored the file manager to work with almond, pinning to either of these hydra-editor commits gives the originally-reported errors. It seems like the refactor just isn't registering in jasmine with or without almond coming through from hydra-editor.

That's all the forensics I have in me. Let me know if this jogs anything for you, @jcoyne or @tpendragon. Tests run on jasmine server in sufia so maybe there is a trick to the difference in setup there.

```
23 specs, 1 failure
Spec List | Failures
FileManager Save Button #persist is called by clicking the save button
Error: No hydra-editor/field_manager
Error: No hydra-editor/field_manager
    at callDep (http://dev.hydra.chemheritage.org:8888/assets/almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js?body=1?body=true:181:19)
    at req (http://dev.hydra.chemheritage.org:8888/assets/almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js?body=1?body=true:342:20)
    at jQuery.$.fn.manage_fields (http://dev.hydra.chemheritage.org:8888/assets/hydra-editor/manage_repeating_fields.self-d6fee0b6a2aefa58f7c2ac3bc3666607df5b4e48a570b0dda3846513414ad538.js?body=1?body=true:27:28)
    at http://dev.hydra.chemheritage.org:8888/assets/hydra-editor/editMetadata.self-c7ac87992156af24f33485bdcead5fbfffe47e54b763c000ba3b4a686ce59e1c.js?body=1?body=true:2:32
    at Object.activate (http://dev.hydra.chemheritage.org:8888/assets/blacklight/core.self-e031fb8c0ca3c81276d0c01490bcff1366bcec5ed64f6901b6a5c229dfd0829f.js?body=1?body=true:10:19)
    at Object.<anonymous> (http://dev.hydra.chemheritage.org:8888/__spec__/save_manager_spec.coffee:56:20)
    at attemptSync (http://dev.hydra.chemheritage.org:8888/__jasmine__/jasmine.js:1886:24)
    at QueueRunner.run (http://dev.hydra.chemheritage.org:8888/__jasmine__/jasmine.js:1874:9)
    at QueueRunner.execute (http://dev.hydra.chemheritage.org:8888/__jasmine__/jasmine.js:1859:10)
    at Spec.queueRunnerFactory (http://dev.hydra.chemheritage.org:8888/__jasmine__/jasmine.js:697:35)
```

**Comment by hackmastera** [comment]
fixed via #941
